services:
  - type: web
    name: api-pima
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "5000"
      - key: REPO_URL
        value: "https://<GITHUB_TOKEN>@github.com/yeifer125/iadatos.git"
      - key: GITHUB_TOKEN
        fromSecret: GITHUB_TOKEN
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/ms-playwright"
